packages = [
  "efibootmgr", # Edit EFI entries
  "killall", # Tool to kill all programs matching process name
  "ncdu", # Terminal disk analyzer
  "nix-health", # Check system health
  "nixfmt-rfc-style", # A nix formatter
  "ntfs3g", # Support NTFS drives
  "p7zip", # 7zip
  "unrar", # Support opening rar files
  "unzip", # An extraction utility
  "wget", # Terminal downloader
]
