packages = [
  "appimage-run", # Appimage runner
  "bat", # Better cat command
  "duf", # Disk usage utility
  "efibootmgr", # Edit EFI entries
  "endeavour", # Tasks
  "fd", # Find alternative
  "flare-signal", # GTK client for Signal
  "fragments", # Bittorrent client following Gnome UI standards
  "ghex", # HEX Editor
  "gimp", # Image editor
  "gping", # ping with a graph
  "iotas", # Notes
  "jc", # JSON parser
  "jq", # JSON parser
  "killall", # Tool to kill all programs matching process name
  "lsd", # Better ls command
  "moonlight-qt", # Remote streaming client
  "mousai", # Song recognizer
  "ncdu", # Terminal disk analyzer
  "newsflash", # RSS reader
  "nix-health", # Check system health
  "nixfmt-rfc-style", # A nix formatter
  "ntfs3g", # Support NTFS drives
  "obs-studio", # Recording/Livestream
  "onlyoffice-bin", # Microsoft Office alternative for Linux
  "p7zip", # 7zip
  "scrcpy", # Remotely use android
  "unrar", # Support opening rar files
  "unzip", # An extraction utility
  "warp", # File sync
  "wget", # Terminal downloader
  "wine", # Compatibility layer capable of running Windows applications
  "winetricks", # Wine prefix settings manager
  "xorg.xhost", # Use x.org server with containers
]
