myPackages = [
  "amberol", # A small and simple sound and music player
  # "audacity", # Sound editor with graphical UI
  # "bun", # Incredibly fast JavaScript runtime, bundler, transpiler and package manager
  "gsound", # Small library for playing system sounds (required to show file properties in Nautilus)
  "handbrake", # Tool for converting video files and ripping DVDs
  "jetbrains.webstorm", # Professional IDE for Web and JavaScript development
  # "nextcloud-client", # Nextcloud themed desktop client
  "pnpm", # Fast, disk space efficient package manager for JavaScript
  "spotify", # Music streaming service
  "sticky-notes", # Simple sticky notes app
  "ungoogled-chromium", # Chromium with dependencies on Google web services removed
  "vesktop", # An open source discord client
]

codingDeps = [
  # "bruno", # API explorer
  # "gcc", # C++ compiler
  # "gdtoolkit_4", # Tools for gdscript
  # "gnumake", # A tool to control the generation of non-source files from sources
  "nixfmt-rfc-style", # A nix formatter
  # "nodejs", # Node package manager
  "python3", # Python
]

packages = [
  # "appimage-run", # Appimage runner
  # "bat", # Better cat command
  "curtail", # Image compressor
  # "duf", # Disk usage utility
  "efibootmgr", # Edit EFI entries
  # "endeavour", # Tasks
  "fd", # Find alternative
  # "flare-signal", # GTK client for Signal
  "fragments", # Bittorrent client following Gnome UI standards
  # "ghex", # HEX Editor
  "gimp", # Image editor
  "gping", # ping with a graph
  # "gthumb", # Image viewer
  # "iotas", # Notes
  # "jc", # JSON parser
  "jq", # JSON parser
  "killall", # Tool to kill all programs matching process name
  "lsd", # Better ls command
  # "moonlight-qt", # Remote streaming client
  "mousai", # Song recognizer
  "ncdu", # Terminal disk analyzer
  "newsflash", # RSS reader
  "nix-health", # Check system health
  "ntfs3g", # Support NTFS drives
  # "obs-studio", # Recording/Livestream
  "onlyoffice-bin", # Microsoft Office alternative for Linux
  "p7zip", # 7zip
  "pavucontrol", # Sound manager
  "scrcpy", # Remotely use android
  "signal-desktop", # Encrypted messaging platform
  # "tree", # Display folder content at a tree format
  "unrar", # Support opening rar files
  "unzip", # An extraction utility
  "warp", # File sync
  "wget", # Terminal downloader
  "wine", # Compatibility layer capable of running Windows applications
  "winetricks", # Wine prefix settings manager
  # "woeusb", # Windows ISO Burner
  "xorg.xhost", # Use x.org server with containers
]
