[icedos.applications]
extraPackages = [
  # "audacity", # Sound editor with graphical UI
  # "bun", # Incredibly fast JavaScript runtime, bundler, transpiler and package manager
  # "curtail", # Image compressor
  "discord-canary", # Bleeding edge version of Discord
  # "eartag", # Simple music tag editor
  "gimp3", # GNU Image Manipulation Program
  "gsound", # Small library for playing system sounds (required to show file properties in Nautilus)
  # "handbrake", # Tool for converting video files and ripping DVDs
  "jetbrains.webstorm", # Professional IDE for Web and JavaScript development
  # "mousai", # Song recognizer
  # "nextcloud-client", # Nextcloud themed desktop client
  "nodejs_20", # Node package manager
  "parabolic", # Download web video and audio
  # "pnpm", # Fast, disk space efficient package manager for JavaScript
  "protonvpn-gui",
  # "spotify", # Music streaming service
  # "sticky-notes", # Simple sticky notes app
  "ungoogled-chromium", # Chromium with dependencies on Google web services removed
  "warp" # File sync
]
insecurePackages = []
aagl = true
android-tools = true
celluloid = true
clamav = false
defaultBrowser = "librewolf" # Options: 'librewolf', 'zen'
defaultEditor = "codium" # Options: 'codium', 'zed'
input-remapper = false
lact = false
librewolf = true
mission-center = false
nautilus = true
php = false
rust = false
solaar = false
ssh = true

[icedos.applications.codium]
enable = true
zoomLevel = 1

[icedos.applications.kitty]
enable = true
hideDecorations = false # Hide top bar

[icedos.applications.mangohud]
enable = false
maxFpsLimit = 165 # Use 0 for unlimited

[icedos.applications.network-manager]
enable = false
applet = true

[icedos.applications.obs-studio]
enable = false
virtualCamera = false

[icedos.applications.ollama]
enable = false
models = ["qwen2.5-coder:latest"] # https://ollama.com/library
rocmOverrideGfx = "10.3.0" # https://github.com/ollama/ollama/blob/main/docs/gpu.md#amd-radeon

[icedos.applications.signal]
enable = true
package = "signal" # Options: 'flare', 'signal'

[icedos.applications.steam]
enable = false
beta = true
downloadsWorkaround = true

[icedos.applications.steam.session]
enable = false
user = "stef"

[icedos.applications.steam.session.autoStart]
enable = false
desktopSession = "hyprland"

[icedos.applications.sunshine]
enable = false
autostart = false

[icedos.applications.tailscale]
enable = false
enableTrayscale = false

[icedos.applications.valent]
enable = false
deviceId = "901524a4_c7c0_407e_9903_431abce54131"

[icedos.applications.zed]
enable = false
vim = false

[icedos.applications.zed.theme]
dark = "One Dark Pro"
light = "One Light"
mode = "system" # Options: 'system', 'dark', 'light'

[icedos.applications.zen-browser]
enable = false
privacy = false

[[icedos.applications.zen-browser.profiles]]
default = false
exec = "default"
pwa = false

[[icedos.applications.zen-browser.profiles]]
default = false
exec = "zen-social"
pwa = true
icon = "zen"
name = "Zen Social"
sites = [
  "https://mail.proton.me",
  "https://develop.element.io",
  "https://discord.com/app",
]

[icedos.bootloader.grub]
enable = false
device = "/dev/sda"

[icedos.bootloader.systemd-boot]
enable = true
mountPoint = "/boot/efi"

[icedos.desktop]
accentColor = "#913A8B" # With gnome enabled this is getting overriden by gnome's selected accent color hex code

[icedos.desktop.autologin]
enable = true
user = "work"

[icedos.desktop.gdm]
enable = true
autoSuspend = true

[icedos.desktop.gnome]
enable = true
accentColor = "purple" # Options: 'blue', 'teal', 'green', 'yellow', 'orange', 'red', 'pink', 'purple', 'slate'
hotCorners = false
powerButtonAction = "interactive"

# Options: 'minimize', 'maximize', 'close', 'spacer'(adds space between buttons), ':'(left-center-right separator)
titlebarLayout = "appmenu:minimize,maximize,close"

[icedos.desktop.gnome.extensions]
arcmenu = true
dashToPanel = true

[icedos.desktop.gnome.clock]
date = true # Show the month and day of the month on the clock
weekday = true # Show the day of the week on the clock

[icedos.desktop.gnome.workspaces]
dynamicWorkspaces = true
maxWorkspaces = 1 # Determines the maximum number of workspaces when dynamic workspaces are disabled

[icedos.desktop.hyprland]
enable = false

[icedos.desktop.hyprland.settings]
followMouse = 2 # Options: https://wiki.hyprland.org/Configuring/Variables/#follow-mouse-cursor
secondsToLowerBrightness = 60
startupScript = """
nautilus -w &
nautilus -w &
signal-desktop &
steam &
zeditor &
zen-beta --no-remote -P default --name zen-startup &
zen-social &
"""
windowRules = [
  "workspace 1 silent, class:^(zen-startup)$",
  "workspace 2 silent, class:^(dev.zed.Zed)$",
  "workspace 11 silent, class:^(signal|zen-social)$",
  "workspace 12 silent, class:^(Steam|steam)$, title:^((?!notificationtoasts.*).)*$",
  "workspace 12 silent, title:^(.*Steam[A-Za-z0-9\\s]*)$",
  "workspace 13 silent, class:^(org\\.gnome\\.Nautilus)$",
]

[icedos.desktop.hyprland.settings.animations]
enable = true
bezierCurve = "0.83, 0, 0.17, 1" # Presets: https://easings.net
speed = 2 # Function: (x * 100)ms

[icedos.desktop.hyprland.plugins]
hyprspace = false

[icedos.desktop.hyprland.plugins.cs2fix]
enable = false
width = 1440
height = 1080

[icedos.desktop.hyprland.plugins.hyproled]
enable = false
startWidth = 0
startHeight = 0
endWidth = 3440
endHeight = 1440

[icedos.hardware]
bluetooth = true

[[icedos.hardware.mounts]]
path = "/"
device = "/dev/disk/by-uuid/a96c8707-e60d-4a63-84e4-a09775df2bec"
fsType = "btrfs"
flags = ["compress=zstd", "nofail", "x-gvfs-show"]

[icedos.hardware.cpus]
intel = false

[icedos.hardware.cpus.amd]
enable = true
zenpower = false # Report watt usage for apps e.g. mangohud

[icedos.hardware.cpus.amd.undervolt]
enable = false
value = "-p 0 -v 40 -f B0" # Pstate 0, 1.15 voltage, 4400 clock speed

[icedos.hardware.devices]
laptop = true
server = false
steamdeck = false

[icedos.hardware.drivers]
rtl8821ce = false # Use the unofficial RTL8821CE driver
xpadneo = false # Xinput bluetooth controller driver

[icedos.hardware.graphics]
enable = true

[icedos.hardware.graphics.amd]
enable = true
rocm = false

[icedos.hardware.graphics.mesa]
unstable = false

[icedos.hardware.graphics.nvidia]
enable = false
beta = false
cuda = false
openDrivers = true

[icedos.hardware.graphics.nvidia.powerLimit]
enable = true
value = 242

[[icedos.hardware.monitors]]
name = "eDP-1"
disable = false
resolution = "1920x1080"
refreshRate = 59.98
position = "0x0"
scaling = 1
rotation = 0
tenBit = false

[icedos.hardware.networking]
hostname = "laptop"
hosts = ""
ipv6 = false
vpnExcludeIp = "192.168.1.201"

[icedos.hardware.networking.wg-quick]
enable = false

interfaces = []

[icedos.system]
channels = [] # https://github.com/NixOS/nixpkgs/branches/active
forceFirstBuild = false
home = "/home"
kernel = "zen" # Options: 'cachyos', 'cachyos-server', 'latest', 'lts', 'valve', 'zen'
swappiness = 1
version = "22.05" # Do not change without checking the docs (config.system.stateVersion)

[icedos.system.generations]
bootEntries = 30

[icedos.system.generations.garbageCollect]
automatic = false
days = 7 # Number of days before a generation can be deleted
generations = 5 # Number of generations that will always be kept
interval = "Mon *-*-* 00:00:00" # Format(https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html)

[icedos.system.users.work]
description = "Work"
type = "work" # Options: 'main', 'work', 'server'

[icedos.system.users.work.applications.codium]
autoSave = "onFocusChange" # Options: 'off', 'afterDelay', 'onFocusChange', 'onWindowChange'
formatOnSave = true
formatOnPaste = false

[icedos.system.users.work.applications.git]
username = "CrazyStevenz"
email = "github.ekta@aleeas.com"

[icedos.system.users.work.desktop.gnome]
startupScript = "protonvpn-app & discordcanary & slack"

[icedos.system.users.work.desktop.gnome.pinnedApps.arcmenu]
enable = true
list = ["codium.desktop"]

# Set pinned apps for gnome shell (will be used by dash-to-panel if enabled)
[icedos.system.users.work.desktop.gnome.pinnedApps.shell]
enable = true
list = [
  "slack.desktop",
  "discord-canary.desktop",
  "signal.desktop",
  "librewolf.desktop",
  "webstorm.desktop",
]

[icedos.system.users.work.desktop.idle.sd-inhibitor]
enable = false

[icedos.system.users.work.desktop.idle.sd-inhibitor.watchers.cpu]
enable = true
threshold = 60 # CPU usage to inhibit lock in percentage

[icedos.system.users.work.desktop.idle.sd-inhibitor.watchers.disk]
enable = true
threshold = 10 # Disk usage to inhibit lock in MB/s

[icedos.system.users.work.desktop.idle.sd-inhibitor.watchers.network]
enable = true
threshold = 1_000_000 # Network usage to inhibit lock in bytes/s

[icedos.system.users.work.desktop.idle.sd-inhibitor.watchers.pipewire]
enable = true
inputsToIgnore = ["Noise Canceling source", "Peak detect", "cava"]
outputsToIgnore = ["Discord", "Element", "Twitch"]

[icedos.system.users.work.desktop.idle.lock]
enable = true
seconds = 270

[icedos.system.users.work.desktop.idle.disableMonitors]
enable = true
seconds = 300

[icedos.system.users.work.desktop.idle.suspend]
enable = false
seconds = 900

[icedos.system.virtualisation]
virtManager = false
waydroid = false

[icedos.system.virtualisation.containerManager]
enable = true
usePodman = true
requireSudoForDocker = true # CAUTION: Disabling this gives every user root priviledges!
