[icedos.applications]
extraPackages = [
  "appimage-run", # Appimage runner
  # "audacity", # Sound editor with graphical UI
  # "bun", # Incredibly fast JavaScript runtime, bundler, transpiler and package manager
  # "curtail", # Image compressor
  "discord-canary", # Bleeding edge version of Discord
  # "eartag", # Simple music tag editor
  "gsound", # Small library for playing system sounds (required to show file properties in Nautilus)
  # "handbrake", # Tool for converting video files and ripping DVDs
  "jetbrains.webstorm", # Professional IDE for Web and JavaScript development
  # "mousai", # Song recognizer
  # "nextcloud-client", # Nextcloud themed desktop client
  "nodejs_20", # Node package manager
  # "parabolic", # Download web video and audio
  # "pnpm", # Fast, disk space efficient package manager for JavaScript
  # "spotify", # Music streaming service
  "sticky-notes", # Simple sticky notes app
  "ungoogled-chromium", # Chromium with dependencies on Google web services removed
]
aagl = true
android-tools = true
brave = false
celluloid = true
clamav = false
defaultBrowser = "librewolf" # Options: 'librewolf', 'zen'
defaultEditor = "codium" # Options: 'codium', 'zed'
falkor = false
fwupd = true
input-remapper = false
mysql = false
nautilus = true
php = false
pitivi = false
protonvpn = true
rust = false
solaar = true
ssh = true
sunshine = false
suyu = false
yazi = false

[icedos.applications.codium]
enable = true
zoomLevel = 1

[icedos.applications.httpd]
enable = false
php = true
user = "icedborn"

[icedos.applications.kitty]
enable = true
hideDecorations = false # Hide top bar

[icedos.applications.librewolf]
enable = true
privacy = false

[icedos.applications.librewolf.pwas]
enable = false
sites = [
  "https://app.tuta.com",
  "https://develop.element.io",
  "https://discord.com/app",
  "https://dtekteam.slack.com/",
  "https://web.skype.com/",
]

[icedos.applications.mangohud]
enable = false
maxFpsLimit = 60 # Use 0 for unlimited

[icedos.applications.mullvad]
enable = false
gui = false

[icedos.applications.network-manager]
enable = false
applet = true

[icedos.applications.obs-studio]
enable = false
virtualCamera = false

[icedos.applications.signal]
enable = true
package = "signal" # Options: 'flare', 'signal'

[icedos.applications.steam]
enable = false
beta = true
downloadsWorkaround = true

[icedos.applications.steam.session]
enable = false
user = "icedborn"

[icedos.applications.steam.session.autoStart]
enable = false
desktopSession = "hyprland"

[icedos.applications.tailscale]
enable = true
enableTrayscale = false

[icedos.applications.valent]
enable = false
deviceId = "901524a4_c7c0_407e_9903_431abce54131"

[icedos.applications.zed]
enable = false
ollamaSupport = false
vim = false

[icedos.applications.zed.theme]
dark = "One Dark Pro"
light = "One Light"
mode = "system" # Options: 'system', 'dark', 'light'

[icedos.applications.zen-browser]
enable = false
privacy = false

[icedos.applications.zen-browser.pwas]
enable = false
sites = [
  "https://mail.proton.me",
  "https://develop.element.io",
  "https://discord.com/app",
  "https://dtekteam.slack.com",
  "https://web.skype.com",
]

[icedos.bootloader]
animation = true # Hides console and displays a loading interface based on OEM on boot

[icedos.bootloader.grub]
enable = false
device = "/dev/sda"

[icedos.bootloader.systemd-boot]
enable = true
mountPoint = "/boot/efi"

[icedos.desktop]
accentColor = "#913A8B" # With gnome enabled this is getting overriden by gnome's selected accent color hex code

[icedos.desktop.autologin]
enable = true
user = "work"

[icedos.desktop.gdm]
enable = true
autoSuspend = true

[icedos.desktop.gnome]
enable = true
accentColor = "purple" # Options: 'blue', 'teal', 'green', 'yellow', 'orange', 'red', 'pink', 'purple', 'slate'
hotCorners = false
powerButtonAction = "interactive"
startupItems = true

# Options: 'minimize', 'maximize', 'close', 'spacer'(adds space between buttons), ':'(left-center-right separator)
titlebarLayout = "appmenu:minimize,maximize,close"

[icedos.desktop.gnome.extensions]
arcmenu = true
dashToPanel = true

[icedos.desktop.gnome.clock]
date = true # Show the month and day of the month on the clock
weekday = true # Show the day of the week on the clock

[icedos.desktop.gnome.workspaces]
dynamicWorkspaces = true
maxWorkspaces = 1 # Determines the maximum number of workspaces when dynamic workspaces are disabled

[icedos.desktop.hyprland]
enable = false
followMouse = 2 # Options: https://wiki.hyprland.org/Configuring/Variables/#follow-mouse-cursor
hyprspace = false

startupScript = """
run protonvpn-app
run zen
run zen-pwas
nautilus -w &
nautilus -w &
run steam
run flare
run zeditor
kitty --class task-managers btop &
kitty --class terminals tmux new -s terminals \\; split-window -v \\; select-pane -U \\; split-window -h \\; select-pane -D &
"""

windowRules = [
  "workspace 1 silent, class:^(zen)$",
  "workspace 2 silent, class:^(dev.zed.Zed)$",
  "workspace 3 silent, class:^(steam_app_.*)$, title:^((?!notificationtoasts.*).)*$",
  "workspace 11 silent, class:^(de.schmidhuberj.Flare|pwas)$",
  "workspace 12 silent, class:^(Steam|steam)$, title:^((?!notificationtoasts.*).)*$",
  "workspace 12 silent, title:^(.*Steam[A-Za-z0-9\\s]*)$",
  "workspace 13 silent, class:^(org\\.gnome\\.Nautilus)$",
  "workspace 14 silent, class:^(task-managers)$",
  "workspace 15 silent, class:^(terminals)$",
]

[icedos.desktop.hyprland.cs2fix]
enable = false
width = 1440
height = 1080

[icedos.desktop.hyprland.hyproled]
enable = true
startWidth = 0
startHeight = 0
endWidth = 3440
endHeight = 1440

[icedos.desktop.hyprland.lock]
secondsToLowerBrightness = 60
cpuUsageThreshold = 60 # CPU usage to inhibit lock in percentage
diskUsageThreshold = 10 # Disk usage to inhibit lock in MB/s
networkUsageThreshold = 1_000_000 # Network usage to inhibit lock in bytes/s

[icedos.hardware]
bluetooth = true
mounts = false # Set to false if hardware/mounts.nix is not correctly configured

[icedos.hardware.btrfs.compression]
enable = true
mounts = false # Use btrfs compression for mounted drives
root = true # Use btrfs compression for / (root)

[icedos.hardware.cpus]
intel = false

[icedos.hardware.cpus.amd]
enable = true

[icedos.hardware.cpus.amd.undervolt]
enable = false
value = "-p 0 -v 40 -f B0" # Pstate 0, 1.15 voltage, 4400 clock speed

[icedos.hardware.devices]
laptop = true
steamdeck = false

[icedos.hardware.drivers]
rtl8821ce = false # Use the unofficial RTL8821CE driver
xpadneo = false # Xbox gamepad bluetooth driver (supports various xinput controllers)

[icedos.hardware.devices.server]
enable = false
dns = "9.9.9.9"
gateway = "192.168.1.1"
interface = "eno1"
ip = "192.168.1.3"

[icedos.hardware.gpus.amd]
enable = true
rocm = false

[icedos.hardware.gpus.nvidia]
enable = false
beta = false
cuda = false
openDrivers = true

[icedos.hardware.gpus.nvidia.powerLimit]
enable = true
value = 242

[[icedos.hardware.monitors]]
name = "eDP-1"
resolution = "1920x1080"
refreshRate = 59.98
position = "0x0"
scaling = 1
rotation = 0
tenBit = false

[icedos.hardware.networking]
hostname = "laptop"
hosts = false
ipv6 = false
vpnExcludeIp = "192.168.1.201"

[icedos.system]
channels = [] # https://github.com/NixOS/nixpkgs/branches/active
forceFirstBuild = false
home = "/home"
kernel = "zen" # Options: 'cachyos', 'cachyos-server', 'latest', 'lts', 'valve', 'zen'
swappiness = 1
version = "22.05" # Do not change without checking the docs (config.system.stateVersion)

[icedos.system.generations]
bootEntries = 30

[icedos.system.generations.garbageCollect]
automatic = false
days = 7 # Number of days before a generation can be deleted
generations = 5 # Number of generations that will always be kept
interval = "Mon *-*-* 00:00:00" # Format(https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html)

[icedos.system.users.work]
description = "Work"
type = "work" # Options: 'main', 'work', 'server'

[icedos.system.users.work.applications.codium]
autoSave = "onFocusChange" # Options: 'off', 'afterDelay', 'onFocusChange', 'onWindowChange'
formatOnSave = true
formatOnPaste = false

[icedos.system.users.work.applications.git]
username = "CrazyStevenz"
email = "github.ekta@aleeas.com"

[icedos.system.users.work.desktop.gnome.pinnedApps.arcmenu]
enable = true
list = ["codium.desktop"]

# Set pinned apps for gnome shell (will be used by dash-to-panel if enabled)
[icedos.system.users.work.desktop.gnome.pinnedApps.shell]
enable = true
list = [
  "slack.desktop",
  "discord-canary.desktop",
  "signal-desktop.desktop",
  "zen.desktop",
  "webstorm.desktop",
]

[icedos.system.users.work.desktop.idle.lock]
enable = true
seconds = 270

[icedos.system.users.work.desktop.idle.disableMonitors]
enable = true
seconds = 300

[icedos.system.users.work.desktop.idle.suspend]
enable = false
seconds = 900

[icedos.system.virtualisation]
libvirtd = false # A daemon that manages virtual machines
waydroid = false # Android container

[icedos.system.virtualisation.containerManager]
enable = true
usePodman = true
requireSudoForDocker = true # CAUTION: Disabling this gives every user root priviledges!
