{
  inputs = {
    # Update channels

    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-unstable";

    };

    # Modules
    home-manager = {
      url = "github:nix-community/home-manager";

      inputs.nixpkgs.follows = "nixpkgs";

    };

    nerivations = {
      url = "github:icedborn/nerivations";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    windsurf = {
      url = "github:KenMacD/etc-nixos";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Apps
    aagl = {
      url = "github:ezKEa/aagl-gtk-on-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    pipewire-screenaudio = {
      url = "github:IceDBorn/pipewire-screenaudio";
      inputs.nixpkgs.follows = "nixpkgs";
    };

  };

  outputs =
    {
      home-manager,
      nerivations,
      windsurf,
      nixpkgs,
      pipewire-screenaudio,
      self,
      aagl,

      ...
    }@inputs:
    {
      nixosConfigurations."laptop" = nixpkgs.lib.nixosSystem rec {
        system = "x86_64-linux";

        specialArgs = {
          inherit inputs;
        };

        modules = [
          # Read configuration location
          (
            { lib, ... }:
            let
              inherit (lib) mkOption types;
            in
            {
              options.icedos.configurationLocation = mkOption {
                type = types.str;
                default = "/home/work/code/IceDOS";
              };
            }
          )

          # Symlink configuration state on "/run/current-system/source"
          {
            # Source: https://github.com/NixOS/nixpkgs/blob/5e4fbfb6b3de1aa2872b76d49fafc942626e2add/nixos/modules/system/activation/top-level.nix#L191
            system.extraSystemBuilderCmds = "ln -s ${self} $out/source";
          }

          # Internal modules
          (
            { lib, ... }:
            let
              inherit (lib) filterAttrs;

              getModules =
                path:
                builtins.map (dir: "/${path}/${dir}") (
                  builtins.attrNames (
                    filterAttrs (n: v: v == "directory" && !(n == "desktop" && path == ./system)) (
                      builtins.readDir path
                    )
                  )
                );
            in
            {
              imports =
                [
                  ./hardware
                  ./internals.nix
                  ./options.nix
                ]
                ++ getModules (./system)
                ++ getModules (./hardware);

              config.system.stateVersion = "22.05";
            }
          )

          # External modules

          home-manager.nixosModules.home-manager
          nerivations.nixosModules.default

          ({
            environment.systemPackages = [ windsurf.packages.${system}.windsurf ];
          })

          ./system/desktop

          # Is First Build
          { icedos.internals.isFirstBuild = false; }

          aagl.nixosModules.default
          {
            nix.settings = aagl.nixConfig; # Set up Cachix
            programs.anime-game-launcher.enable = true; # Adds launcher and /etc/hosts rules
          }

          ./system/desktop/gnome

          ./system/users/work

          (
            # Do not modify this file!  It was generated by ‘nixos-generate-config’
            # and may be overwritten by future invocations.  Please make changes
            # to /etc/nixos/configuration.nix instead.
            {
              config,
              lib,
              pkgs,
              modulesPath,
              ...
            }:

            {
              imports = [
                (modulesPath + "/installer/scan/not-detected.nix")
              ];

              boot.initrd.availableKernelModules = [
                "nvme"
                "xhci_pci"
                "ahci"
                "usb_storage"
                "sd_mod"
              ];
              boot.initrd.kernelModules = [ ];
              boot.kernelModules = [ "kvm-amd" ];
              boot.extraModulePackages = [ ];

              fileSystems."/" = {
                device = "/dev/disk/by-uuid/a96c8707-e60d-4a63-84e4-a09775df2bec";
                fsType = "btrfs";
                options = [ "subvol=@" ];
              };

              boot.initrd.luks.devices."luks-1a3c2842-eb46-4f8f-9960-716acabc4b31".device =
                "/dev/disk/by-uuid/1a3c2842-eb46-4f8f-9960-716acabc4b31";
              boot.initrd.luks.devices."luks-a8cffca7-e268-4cb1-a7b8-2e14a3b56208".device =
                "/dev/disk/by-uuid/a8cffca7-e268-4cb1-a7b8-2e14a3b56208";

              fileSystems."/boot/efi" = {
                device = "/dev/disk/by-uuid/7330-238A";
                fsType = "vfat";
              };

              swapDevices = [
                { device = "/dev/disk/by-uuid/edb966ac-b852-4051-bc93-668b968849a7"; }
              ];

              # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
              # (the default) this is the recommended approach. When using systemd-networkd it's
              # still possible to use this option, but it's recommended to use it in conjunction
              # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
              networking.useDHCP = lib.mkDefault true;
              # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
              # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

              nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
              hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
            }
          )

          ({ })

        ];
      };
    };
}
