myPackages = [
  "nodejs_18", # Node package manager
  "nodePackages.firebase-tools", # Manage, and deploy your Firebase project from the command line
  "slack", # Desktop client for Slack
  "watchman", # Watches files and takes action when they change
]

packages = [
  "beekeeper-studio", # SQL client
  # "php", # An HTML-embedded scripting language
  # "phpPackages.composer", # Dependency Manager for PHP
]
